#Time until torch will be unlit
resetTime: 60
#The name of the permanent torch
permaTorch: "&fPermanent Torch"
#Should the players be able to craft the permanent torch?
enableCrafting: true
#Use coal blocks instead of coal for crafting?
expensiveCrafting: false

#If players with this permission place torches they will not go out.
#If those torches are broken they will turn into normal torches.
#Permanent torches behave as usual.
permanentPermission: "torch.permanent"
#Should the permission be enabled. If false the permission will not be used
enablePermanentPermission: false

#If players with game mode creative place torches they will not go out.
#If those torches are broken they will turn into normal torches.
#Permanent torches behave as usual.
enableCreativePermanent: true